project_name: redskyctl
before:
  hooks:
    - go mod tidy
builds:
  - dir: redskyctl
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    ldflags:
      - '-s -w'
      - '-X github.com/thestormforge/optimize-controller/internal/version.Version=v{{ .Version }}'
      - '-X github.com/thestormforge/optimize-controller/internal/version.GitCommit={{ .FullCommit }}'
      - '-X github.com/thestormforge/optimize-controller/internal/version.BuildMetadata={{ .Env.BUILD_METADATA }}'
      - '-X github.com/thestormforge/optimize-controller/internal/setup.Image={{ .Env.SETUPTOOLS_IMG }}'
      - '-X github.com/thestormforge/optimize-controller/internal/setup.ImagePullPolicy={{ .Env.PULL_POLICY }}'
      - '-X github.com/thestormforge/optimize-controller/redskyctl/internal/kustomize.BuildImage={{ .Env.IMG }}'
    hooks:
      post:
        - hack/codesign.sh "{{ .Path }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: '{{ replace .Tag "v" "" }}-next'
release:
  draft: true
archives:
  - name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
    files:
      - none*
dockers:
  - image_templates:
      - '{{ .Env.REDSKYCTL_IMG }}'
    build_flag_templates:
      - "--label=org.opencontainers.image.source={{.GitURL}}"
    dockerfile: redskyctl/Dockerfile
brews:
  - tap:
      owner: thestormforge
      name: homebrew-tap
    folder: Formula
    commit_author:
      name: Butch Masters
      email: butch@carbonrelay.com
    homepage: "https://www.stormforge.io/"
    description: Release with Confidence
signs:
  - id: notarization
    # This is going to produce empty ".sig" files that will need to be manually removed from the GitHub release
    cmd: hack/notarize.sh
    args: ["${artifact}", "${signature}"]
    artifacts: all
