before:
  hooks:
    - go mod tidy
builds:
  - dir: cli
    binary: stormforge
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    ignore:
    - goos: linux
      goarch: arm64
    ldflags:
      - '-s -w'
      - '-X github.com/thestormforge/optimize-controller/v2/internal/version.Version=v{{ .Version }}'
      - '-X github.com/thestormforge/optimize-controller/v2/internal/version.GitCommit={{ .FullCommit }}'
      - '-X github.com/thestormforge/optimize-controller/v2/internal/version.BuildMetadata={{ .Env.BUILD_METADATA }}'
      - '-X github.com/thestormforge/optimize-controller/v2/internal/setup.Image={{ .Env.SETUPTOOLS_IMG }}'
      - '-X github.com/thestormforge/optimize-controller/v2/internal/setup.ImagePullPolicy={{ .Env.PULL_POLICY }}'
      - '-X github.com/thestormforge/optimize-controller/v2/cli/internal/kustomize.BuildImage={{ .Env.IMG }}'
    hooks:
      post:
        - hack/codesign.sh "{{ .Path }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: '{{ replace .Tag "v" "" }}-next'
release:
  draft: true
archives:
  - name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
    files:
      - none*
