apiVersion: redskyops.dev/v1beta1
kind: Experiment
metadata:
  name: ci
spec:
  parameters:
  - name: something
    min: 50
    max: 1000
    baseline: 100
  - name: another
    min: 16
    max: 512
    baseline: 64
  metrics:
  - minimize: true
    name: cost
    port: 9090
    query: ({{ cpuRequests . "redskyops.dev/trial-role=trialResource" }} * 1) + ({{ memoryRequests . "redskyops.dev/trial-role=trialResource" | GB }} * 1)
    type: prometheus
  trialTemplate:
    spec:
      approximateRuntime: 45s
      setupServiceAccountName: redsky-setup
      setupTasks:
      - args:
        - prometheus
        - $(MODE)
        name: monitoring

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    redskyops.dev/application: ci
  name: redsky-setup
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    redskyops.dev/application: ci
  name: redsky-prometheus
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - get
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - services
  - configmaps
  verbs:
  - get
  - create
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - create
  - delete
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/metrics
  - nodes/proxy
  - services
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    redskyops.dev/application: ci
  name: redsky-setup-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redsky-prometheus
subjects:
- kind: ServiceAccount
  name: redsky-setup
  namespace: default
