---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: optimize
    app.kubernetes.io/managed-by: stormforge
    app: prometheus
  name: "optimize-{{ .Release.Namespace }}-prometheus"
spec:
  ports:
  - name: server
    port: 9090
    protocol: TCP
    targetPort: 9090
  - name: pushgw
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    app.kubernetes.io/name: optimize
    app.kubernetes.io/managed-by: stormforge
    app: prometheus
  sessionAffinity: None
  type: ClusterIP
