---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus
    helm.sh/chart: optimize-prometheus
    app.kubernetes.io/name: optimize-prometheus
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
  name: {{ .Release.Name }}-server
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: prometheus
    helm.sh/chart: optimize-prometheus
    app.kubernetes.io/name: optimize-prometheus
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
  name: {{ .Release.Name }}-server
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-server
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-server
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: prometheus
    helm.sh/chart: optimize-prometheus
    app.kubernetes.io/name: optimize-prometheus
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
  name: {{ .Release.Name }}-server
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
    - ""
    resources:
    - nodes
    - nodes/proxy
    - nodes/metrics
    - services
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - list
    - watch

