name: Pull Request
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      - name: Run tests
        run: make test

  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      BUILD_METADATA: build.${{ github.run_number }}
      GIT_COMMIT: ${{ github.sha }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      # Launch KinD early so we can do other things while the control plane converges
      - name: KinD (Kubernetes in Docker) Initialization
        uses: helm/kind-action@v1.1.0
        with:
          version: v0.11.1
          wait: 0s
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      - name: Set up GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          install-only: true
      - name: Bootstrap
        run: |
          DOCKER_REGISTRY="ghcr.io/thestormforge"
          DOCKER_TAG="sha-$(git rev-parse --short HEAD)"
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login "ghcr.io" -u "${{ github.actor }}" --password-stdin
          echo "IMAGE_TAG=pr-${{ github.event.number }}" >> $GITHUB_ENV
          echo "IMG=${DOCKER_REGISTRY}/optimize-controller:${DOCKER_TAG}" >> $GITHUB_ENV
          echo "SETUPTOOLS_IMG=${DOCKER_REGISTRY}/setuptools:${DOCKER_TAG}" >> $GITHUB_ENV
          echo "PULL_POLICY=" >> $GITHUB_ENV
      - name: Build controller
        run: |
          make -o test docker-build
      - name: Push Docker images
        if: github.event.pull_request.head.repo.fork == false
        run: |
          make docker-push
          docker-push() {
            docker tag "$1" "$2"
            docker push "$2"
          }
          docker-push "${IMG}" "${IMG%%:*}:${IMAGE_TAG}"
          docker-push "${SETUPTOOLS_IMG}" "${SETUPTOOLS_IMG%%:*}:${IMAGE_TAG}"
      - name: Run integration tests
        run: hack/integration.sh
