name: Release
on:
  push:
    tags:
    - v*

jobs:

  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      BUILD_METADATA: build.${{ github.run_number }}
      GIT_COMMIT: ${{ github.sha }}
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
        cache: true

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: '${{ github.actor }}'
        password: '${{ github.token }}'

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: '${{ secrets.DOCKERHUB_USERNAME }}'
        password: '${{ secrets.DOCKERHUB_TOKEN }}'

    - name: Build and push controller
      run: |
        VERSION="${GITHUB_REF_NAME}"
        IMG="thestormforge/optimize-controller:${GITHUB_REF_NAME#v}"
        SETUPTOOLS_IMG="thestormforge/setuptools:${GITHUB_REF_NAME#v}"
        PULL_POLICY=""
        
        make -o test docker-build
        make docker-push
        
        skopeo copy "docker://${IMG}" "docker://${IMG%%:*}:latest"
        skopeo copy "docker://${IMG}" "docker://ghcr.io/${IMG}"
        skopeo copy "docker://${IMG}" "docker://ghcr.io/${IMG%%:*}:latest"
        skopeo copy "docker://${SETUPTOOLS_IMG}" "docker://${SETUPTOOLS_IMG%%:*}:latest"
        skopeo copy "docker://${SETUPTOOLS_IMG}" "docker://ghcr.io/${SETUPTOOLS_IMG}"
        skopeo copy "docker://${SETUPTOOLS_IMG}" "docker://ghcr.io/${SETUPTOOLS_IMG%%:*}:latest"

    - name: Update Helm Chart
      env:
        GH_TOKEN: ${{ secrets.BMASTERS_TOKEN }}
        GH_REPO: thestormforge/helm-charts
      run: gh workflow run build.yaml --ref main -f image_tag=${GITHUB_REF_NAME#v}
