name: Release

on:
  release:
    types: [published]

jobs:

  helmChart:
    runs-on: ubuntu-latest
    steps:
    - name: Update Helm Chart
      env:
        GH_TOKEN: ${{ secrets.BMASTERS_TOKEN }}
        GH_REPO: thestormforge/helm-charts
        IMAGE_TAG: ${{ github.event.release.tag_name }}
      run: gh workflow run build.yaml --ref main -f image_tag=${IMAGE_TAG#v}
